Add files via upload

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # xrepcim00
-# 9.3.2024
+# 13.3.2024
 
 # Set POSIX to yes
 export POSIXLY_CORRECT=yes
@@ -93,9 +93,6 @@ parse_arguments() {
 
 # Function that checks parsed arguments
 check_arguments() {
-    # Define a regular expression pattern to match the correct date-time format
-    local datetime_pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}$'
-
     # Check if user is specified
     if [[ -z "$user" ]]; then
         echo "Error: User is not specified." >&2
@@ -109,7 +106,8 @@ check_arguments() {
     fi
 
     # Check if date format is correct
-    if ! [[ $date_before =~ $datetime_pattern && $date_after =~ $datetime_pattern ]]; then
+    if ! date -d "$date_before" +"%Y-%m-%d %H:%M:%S" >/dev/null 2>&1 || \
+        ! date -d "$date_after" +"%Y-%m-%d %H:%M:%S" >/dev/null 2>&1; then
         echo "Error: Datetime format is incorrect." >&2
         exit 1
     fi
@@ -151,9 +149,45 @@ execute_command() {
     esac
 }
 
+# Function that checks if the content of the file is correct
+check_file() {
+    local logfile="$1"
+
+    while IFS=';' read -r name date currency value; do
+        # Check if any field is missing
+        if [[ -z "$name" || -z "$date" || -z "$currency" || -z "$value" ]]; then
+            #echo "Error: Missing field in $logfile"
+            exit 1
+        fi
+        # Check name format
+        if [[ "$name" =~ [[:space:]] ]]; then
+            #echo "Error: Invalid name format in $logfile"
+            exit 1
+        fi
+        # Check date format
+        if ! date -d "$date" "+%Y-%m-%d %H:%M:%S" >/dev/null 2>&1; then
+            #echo "Error: Invalid date format in $logfile"
+            exit 1
+        fi
+        # Check currency format
+        if ! [[ "$currency" =~ ^[A-Za-z]{3}$ ]]; then
+            #echo "Error: Invalid currency format in $logfile"
+            exit 1
+        fi
+        # Check value format
+        if ! [[ "$value" =~ ^-?[0-9]+(\.[0-9]{4})?$ ]]; then
+            #echo "Error: Invalid value format in $logfile"
+            exit 1
+        fi
+    done < "$logfile"
+
+    return 0
+}
+
 # Function that applies filters
 apply_filters() {
     local logfile="$1"
+    check_file "$logfile"
     # Create awk script that appends filters
     local awk_script="BEGIN { FS = \";\" }"
     # Append user filter
@@ -249,8 +283,8 @@ main() {
     user=""
     log_files=()
     # Set default filters
-    date_before="9999-99-99 99:99:99"
-    date_after="0000-00-00 00:00:00"
+    date_before="9999-12-31 23:59:59"
+    date_after="0000-01-01 00:00:00"
     filter_currency=()
 
     parse_arguments "$@"
